project_id = "qjidxedogekxxdjitdda"

[functions.chat]
verify_jwt = true

[functions.generate-image]
verify_jwt = true

[functions.edit-image]
verify_jwt = true

[functions.enhance-prompt]
verify_jwt = true

[functions.image-to-prompt]
verify_jwt = true

[functions.remix-images]
verify_jwt = true